version: '3'

services:
      db:
        image: mysql:5.7
        ports:
          - 3306:3306
        environment:
          MYSQL_DATABASE: 'myproject'
          MYSQL_USER: 'myprojectuser'
          MYSQL_PASSWORD: 'password'
          MYSQL_ROOT_PASSWORD: 'password'
      web:
          build: .
          command: gunicorn FUNDOONOTES.wsgi:application --bind 0.0.0.0:8000
          expose:
              - 8000
      nginx:
        build: ./nginx
        ports:
          - 1337:80
        depends_on:
          - web