version: '3'

services:
      db:
        image: mysql:5.7
        ports:
          - 3306:3306
        environment:
          MYSQL_DATABASE: 'my-app-db'
          MYSQL_USER: 'root'
          MYSQL_PASSWORD: 'kartikey@123'
          MYSQL_ROOT_PASSWORD: 'kartkey@123'
      web:
          build: .
          command: python manage.py runserver 0.0.0.0:8000
          ports:
              - 8000:8000