version: '3'

services:
      db:
        image: mysql:5.7
        ports:
          - 3306:3306
        environment:
          MYSQL_DATABASE: 'myproject'
          MYSQL_ROOT_PASSWORD: 'password'
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        volumes:
          - ./config/redis.conf:/redis.conf
        command: [ "redis-server", "/redis.conf" ]
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.8.10
        container_name: elasticsearch
        ports:
          - 9200:9200
        volumes:
        - ./fundoonotes/documents.py:/documents.py
      web:
        restart: always
        build: .
        command: gunicorn FUNDOONOTES.wsgi:application --bind 0.0.0.0:8000
                 #python manage.py runserver 0.0.0.0:8000
#        volumes:
#          - ./:/FUNDOOAPP
#        ports:
#          - "8000:8000"
        expose:
          - 8000
        depends_on:
          - db
      nginx:
        build: ./nginx
        ports:
          - 1337:80
        depends_on:
          - web
      adminer:
        image: adminer
        restart: always
        ports:
          - 8080:8080

#volumes:
#    mysql_data:


