# Generated by Django 2.2 on 2020-05-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=49, verbose_name='name_of_label')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=999)),
                ('note', models.CharField(max_length=2999)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('reminder', models.DateTimeField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
                ('is_archive', models.BooleanField(default=False, verbose_name='is_archive')),
                ('is_trashed', models.BooleanField(default=False, verbose_name='is_trashed')),
                ('is_pin', models.BooleanField(default=False, verbose_name='is_pin')),
            ],
        ),
    ]
